In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [6]:
# Read in file
df = pd.read_csv('data/2022/EDUCATIONAL_ATTAINMENT.CSV')
df

                                                Label Estimate Margin of Error
0                        Population 25 years and over   66,048          ±5,730
1                       Less than high school diploma     2.9%            ±1.0
2           High school graduate (includes equival...     6.3%            ±1.8
3                  Some college or associate's degree    23.2%            ±2.9
4                                   Bachelor's degree    53.9%            ±3.5
5                     Graduate or professional degree    13.9%            ±2.5
6                      High school graduate or higher    97.1%            ±1.0
7                Male, high school graduate or higher    98.2%            ±1.0
8               Female, high school graduate or hi...    96.4%            ±1.7
9                         Bachelor's degree or higher    67.7%            ±3.2
10                  Male, bachelor's degree or higher    61.9%            ±5.2
11                Female, bachelor's degree or higher    72.0%            ±3.6

In [7]:
# Get rid of spaces in Labels
df['Label'] = df['Label'].apply(lambda x: x.lstrip())
df

                                          Label Estimate Margin of Error
0                  Population 25 years and over   66,048          ±5,730
1                 Less than high school diploma     2.9%            ±1.0
2   High school graduate (includes equivalency)     6.3%            ±1.8
3            Some college or associate's degree    23.2%            ±2.9
4                             Bachelor's degree    53.9%            ±3.5
5               Graduate or professional degree    13.9%            ±2.5
6                High school graduate or higher    97.1%            ±1.0
7          Male, high school graduate or higher    98.2%            ±1.0
8        Female, high school graduate or higher    96.4%            ±1.7
9                   Bachelor's degree or higher    67.7%            ±3.2
10            Male, bachelor's degree or higher    61.9%            ±5.2
11          Female, bachelor's degree or higher    72.0%            ±3.6

In [8]:
# Convert percentage estimates to float
df['Percentage'] = df['Estimate'].apply(lambda x: float(x.rstrip('%'))/100 if '%' in x else None)
df

,Label,Estimate,Margin of Error,Percentage
0,Population 25 years and over,"66,048","±5,730",NaN
1,Less than high school diploma,2.9%,±1.0,0.029
2,High school graduate (includes equivalency),6.3%,±1.8,0.063
3,Some college or associate's degree,23.2%,±2.9,0.232
4,Bachelor's degree,53.9%,±3.5,0.539
5,Graduate or professional degree,13.9%,±2.5,0.139
6,High school graduate or higher,97.1%,±1.0,0.971
7,"Male, high school graduate or higher",98.2%,±1.0,0.982
8,"Female, high school graduate or higher",96.4%,±1.7,0.964
9,Bachelor's degree or higher,67.7%,±3.2,0.677
10,"Male, bachelor's degree or higher",61.9%,±5.2,0.619
11,"Female, bachelor's degree or higher",72.0%,±3.6,0.720

In [9]:
# Keep only individual population stats
df = df.iloc[:6]
df

,Label,Estimate,Margin of Error,Percentage
0,Population 25 years and over,"66,048","±5,730",NaN
1,Less than high school diploma,2.9%,±1.0,0.029
2,High school graduate (includes equivalency),6.3%,±1.8,0.063
3,Some college or associate's degree,23.2%,±2.9,0.232
4,Bachelor's degree,53.9%,±3.5,0.539
5,Graduate or professional degree,13.9%,±2.5,0.139

In [ ]:
def education(file,year):
    # Read in file
    df = pd.read_csv(file)

    # Get rid of spaces in Labels
    df['Label'] = df['Label'].apply(lambda x: x.lstrip())

    # Convert percentage estimates to float
    df['Percentage'] = df['Estimate'].apply(lambda x: float(x.rstrip('%'))/100 if '%' in x else None)

    # Keep only individual population stats
    df = df.iloc[:6]

    # Move Total Population 16+ from row to column
    df['Total Population 16+'] = int(df.iloc[0]['Estimate'].replace(',',''))
    df.dropna(inplace=True)

    # Drop unnecessary columns
    df.drop(columns=['Estimate','Margin of Error'], inplace=True)

    # Calculate population estimates
    df['Population Estimate'] = df['Percentage']*df['Total Population 16+']

    # Drop unnecessary columns
    df.drop(columns=['Percentage','Total Population 16+'], inplace=True)

    # Change index and transpose table
    df.set_index('Label', inplace=True)
    df = df.T

    # Drop unnecessary colummns
    try:
        df.drop(columns=['In labor force','Civilian labor force','Unemployment Rate'], inplace=True)
    except:
        df.drop(columns=['In labor force','Civilian labor force','Percent of civilian labor force'], inplace=True)

    # Change index to year
    df.index = [year]

    # Calculate extra columns
    df['Total Population 16+'] = df.sum(axis=1)
    df['Unemployment Rate'] = df['Unemployed']/(df['Total Population 16+']-df['Not in labor force'])

    return df