In [28]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [29]:
df = pd.read_csv('data/2010/INCOME_IN_THE_PAST_12_MONTHS_IN_2010_INFLATIONADJUSTED_DOLLARS.CSV')

In [30]:
df

                                                Label Estimate Margin of Error
0                                          Households   24,310          ±2,322
1                   Median household income (dollars)   78,863          ±9,131
2                                       With earnings    92.9%            ±3.0
3                             Mean earnings (dollars)   88,225          ±7,498
4                         With Social Security income    21.2%            ±4.2
5               Mean Social Security income (dollars)   17,355          ±2,524
6                   With Supplemental Security Income     2.7%            ±1.9
7           Mean Supplemental Security Income (dol...    6,823          ±4,173
8                  With cash public assistance income     2.5%            ±1.8
9           Mean cash public assistance income (do...    1,910            ±816
10                             With retirement income    10.2%            ±3.5
11                   Mean retirement income (dollars)   25,657          ±9,123
12                      With Food Stamp/SNAP benefits     5.9%            ±2.6
13                                           Families   17,208          ±1,995
14                     Median family income (dollars)   90,060          ±8,725
15                              Married-couple family    77.9%            ±5.6
16                            Median income (dollars)   95,909          ±7,886
17          Male householder, no spouse present, f...     3.4%            ±2.6
18                            Median income (dollars)        N               N
19          Female householder, no husband present...    18.7%            ±5.8
20                            Median income (dollars)   72,307         ±22,179
21                                        Individuals   72,344          ±6,851
22                        Per capita income (dollars)   31,626          ±3,039
23      With earnings for full-time, year-round wo...      NaN             NaN
24                                               Male   14,087          ±2,089
25                                             Female   16,849          ±2,396
26          Mean earnings (dollars) for full-time,...      NaN             NaN
27                                               Male   56,440          ±6,535
28                                             Female   58,708          ±6,053
29          Median earnings (dollars) full-time, y...      NaN             NaN
30                                               Male   46,376          ±4,682
31                                             Female   51,444          ±4,080

In [31]:
df['Label'] = df['Label'].apply(lambda x: x.lstrip())

In [32]:
df_1 = df.iloc[:16]

In [33]:
df_1['Estimate'] = df_1['Estimate'].apply(lambda x: x.rstrip('%'))
df_1['Estimate'] = df_1['Estimate'].apply(lambda x: x.replace(',', ''))

In [34]:
# change the estimate column to float
df_1['Estimate'] = df_1['Estimate'].astype(float)

In [35]:
df_1.drop(columns=['Margin of Error'], inplace=True)

In [36]:
df_1.set_index('Label', inplace=True)

In [37]:
df_2 = df_1.T

In [38]:
df_2

Label,Households,Median household income (dollars),With earnings,Mean earnings (dollars),With Social Security income,Mean Social Security income (dollars),With Supplemental Security Income,Mean Supplemental Security Income (dollars),With cash public assistance income,Mean cash public assistance income (dollars),With retirement income,Mean retirement income (dollars),With Food Stamp/SNAP benefits,Families,Median family income (dollars),Married-couple family
Estimate,24310.0,78863.0,92.9,88225.0,21.2,17355.0,2.7,6823.0,2.5,1910.0,10.2,25657.0,5.9,17208.0,90060.0,77.9

In [59]:
def income_past_12_months(file, year):
    df = pd.read_csv(file)
    df['Label'] = df['Label'].apply(lambda x: x.lstrip())
    df_1 = df.iloc[:16]
    df_1['Estimate'] = df_1['Estimate'].apply(lambda x: x.rstrip('%'))
    df_1['Estimate'] = df_1['Estimate'].apply(lambda x: x.replace(',', ''))
    df_1['Estimate'] = df_1['Estimate'].astype(float)
    df_1.drop(columns=['Margin of Error'], inplace=True)
    df_1.set_index('Label', inplace=True)
    df_2 = df_1.T
    df_2.index = [year]
    return df_2

In [60]:
for year in range(2010, 2023):
    file = 'data/' + str(year) + '/INCOME_IN_THE_PAST_12_MONTHS_IN_' + str(year) + '_INFLATIONADJUSTED_DOLLARS.CSV'
    
    try: 
        income_past_12_months(file, year)
    except:
        print(f"No file for year '{year}'")

No file for year '2016'
No file for year '2018'
No file for year '2020'

In [61]:
income_past_12_months('data/2010/INCOME_IN_THE_PAST_12_MONTHS_IN_2010_INFLATIONADJUSTED_DOLLARS.CSV', 2010)

Label,Households,Median household income (dollars),With earnings,Mean earnings (dollars),With Social Security income,Mean Social Security income (dollars),With Supplemental Security Income,Mean Supplemental Security Income (dollars),With cash public assistance income,Mean cash public assistance income (dollars),With retirement income,Mean retirement income (dollars),With Food Stamp/SNAP benefits,Families,Median family income (dollars),Married-couple family
2010,24310.0,78863.0,92.9,88225.0,21.2,17355.0,2.7,6823.0,2.5,1910.0,10.2,25657.0,5.9,17208.0,90060.0,77.9

In [62]:
INCOME_PAST_2022 = income_past_12_months('data/2022/INCOME_IN_THE_PAST_12_MONTHS_IN_2022_INFLATIONADJUSTED_DOLLARS.CSV', 2022)
INCOME_PAST_2021 = income_past_12_months('data/2021/INCOME_IN_THE_PAST_12_MONTHS_IN_2021_INFLATIONADJUSTED_DOLLARS.CSV', 2021)
INCOME_PAST_2019 = income_past_12_months('data/2019/INCOME_IN_THE_PAST_12_MONTHS_IN_2019_INFLATIONADJUSTED_DOLLARS.CSV', 2019)
INCOME_PAST_2017 = income_past_12_months('data/2017/INCOME_IN_THE_PAST_12_MONTHS_IN_2017_INFLATIONADJUSTED_DOLLARS.CSV', 2017)
INCOME_PAST_2015 = income_past_12_months('data/2015/INCOME_IN_THE_PAST_12_MONTHS_IN_2015_INFLATIONADJUSTED_DOLLARS.CSV', 2015)
INCOME_PAST_2014 = income_past_12_months('data/2014/INCOME_IN_THE_PAST_12_MONTHS_IN_2014_INFLATIONADJUSTED_DOLLARS.CSV', 2014)
INCOME_PAST_2013 = income_past_12_months('data/2013/INCOME_IN_THE_PAST_12_MONTHS_IN_2013_INFLATIONADJUSTED_DOLLARS.CSV', 2013)
INCOME_PAST_2012 = income_past_12_months('data/2012/INCOME_IN_THE_PAST_12_MONTHS_IN_2012_INFLATIONADJUSTED_DOLLARS.CSV', 2012)
INCOME_PAST_2011 = income_past_12_months('data/2011/INCOME_IN_THE_PAST_12_MONTHS_IN_2011_INFLATIONADJUSTED_DOLLARS.CSV', 2011)
INCOME_PAST_2010 = income_past_12_months('data/2010/INCOME_IN_THE_PAST_12_MONTHS_IN_2010_INFLATIONADJUSTED_DOLLARS.CSV', 2010)

In [63]:
INCOME_PAST_12_MONTHS_STATUS = pd.concat([INCOME_PAST_2010, INCOME_PAST_2011, INCOME_PAST_2012, INCOME_PAST_2013, INCOME_PAST_2014, INCOME_PAST_2015, INCOME_PAST_2017, INCOME_PAST_2019, INCOME_PAST_2021, INCOME_PAST_2022])
INCOME_PAST_12_MONTHS_STATUS

Label,Households,Median household income (dollars),With earnings,Mean earnings (dollars),With Social Security income,Mean Social Security income (dollars),With Supplemental Security Income,Mean Supplemental Security Income (dollars),With cash public assistance income,Mean cash public assistance income (dollars),With retirement income,Mean retirement income (dollars),With Food Stamp/SNAP benefits,Families,Median family income (dollars),Married-couple family
2010,24310.0,78863.0,92.9,88225.0,21.2,17355.0,2.7,6823.0,2.5,1910.0,10.2,25657.0,5.9,17208.0,90060.0,77.9
2011,22701.0,82387.0,94.7,91562.0,18.8,16029.0,2.8,9095.0,3.3,6897.0,7.2,23199.0,2.9,15107.0,90562.0,78.2
2012,23724.0,86429.0,92.0,98921.0,19.7,17122.0,2.9,7130.0,1.4,3208.0,10.0,57828.0,4.2,17179.0,89085.0,72.2
2013,26959.0,75459.0,89.9,91695.0,25.3,18454.0,4.3,6401.0,1.9,2231.0,8.3,21639.0,7.8,18855.0,82036.0,70.0
2014,22226.0,90424.0,91.6,97772.0,22.9,19799.0,3.5,7285.0,2.4,3467.0,11.8,20909.0,7.4,16003.0,96734.0,78.9
2015,25286.0,85545.0,92.1,100788.0,20.6,22370.0,4.1,7439.0,2.5,2198.0,10.1,31051.0,7.6,17532.0,94014.0,78.3
2017,26139.0,80633.0,88.0,107240.0,26.9,18420.0,3.5,9327.0,2.5,2282.0,8.9,24875.0,5.3,18198.0,88280.0,67.6
2019,26642.0,99311.0,90.0,107921.0,25.6,22222.0,2.0,13075.0,2.5,2642.0,22.1,33649.0,6.1,18304.0,102069.0,79.3
2021,29191.0,100098.0,87.9,114198.0,26.9,21673.0,3.7,7721.0,5.5,5881.0,19.8,26053.0,7.8,20642.0,113072.0,80.7
2022,32190.0,107149.0,88.4,138669.0,25.2,22259.0,2.6,10556.0,1.8,1316.0,21.4,37426.0,10.5,23121.0,116764.0,71.5

In [64]:
INCOME_PAST_12_MONTHS_STATUS.reset_index(inplace=True)
INCOME_PAST_12_MONTHS_STATUS.rename(columns={'index': 'Year'}, inplace=True)
INCOME_PAST_12_MONTHS_STATUS

Label,Year,Households,Median household income (dollars),With earnings,Mean earnings (dollars),With Social Security income,Mean Social Security income (dollars),With Supplemental Security Income,Mean Supplemental Security Income (dollars),With cash public assistance income,Mean cash public assistance income (dollars),With retirement income,Mean retirement income (dollars),With Food Stamp/SNAP benefits,Families,Median family income (dollars),Married-couple family
0,2010,24310.0,78863.0,92.9,88225.0,21.2,17355.0,2.7,6823.0,2.5,1910.0,10.2,25657.0,5.9,17208.0,90060.0,77.9
1,2011,22701.0,82387.0,94.7,91562.0,18.8,16029.0,2.8,9095.0,3.3,6897.0,7.2,23199.0,2.9,15107.0,90562.0,78.2
2,2012,23724.0,86429.0,92.0,98921.0,19.7,17122.0,2.9,7130.0,1.4,3208.0,10.0,57828.0,4.2,17179.0,89085.0,72.2
3,2013,26959.0,75459.0,89.9,91695.0,25.3,18454.0,4.3,6401.0,1.9,2231.0,8.3,21639.0,7.8,18855.0,82036.0,70.0
4,2014,22226.0,90424.0,91.6,97772.0,22.9,19799.0,3.5,7285.0,2.4,3467.0,11.8,20909.0,7.4,16003.0,96734.0,78.9
5,2015,25286.0,85545.0,92.1,100788.0,20.6,22370.0,4.1,7439.0,2.5,2198.0,10.1,31051.0,7.6,17532.0,94014.0,78.3
6,2017,26139.0,80633.0,88.0,107240.0,26.9,18420.0,3.5,9327.0,2.5,2282.0,8.9,24875.0,5.3,18198.0,88280.0,67.6
7,2019,26642.0,99311.0,90.0,107921.0,25.6,22222.0,2.0,13075.0,2.5,2642.0,22.1,33649.0,6.1,18304.0,102069.0,79.3
8,2021,29191.0,100098.0,87.9,114198.0,26.9,21673.0,3.7,7721.0,5.5,5881.0,19.8,26053.0,7.8,20642.0,113072.0,80.7
9,2022,32190.0,107149.0,88.4,138669.0,25.2,22259.0,2.6,10556.0,1.8,1316.0,21.4,37426.0,10.5,23121.0,116764.0,71.5

In [66]:
INCOME_PAST_2010

Label,Households,Median household income (dollars),With earnings,Mean earnings (dollars),With Social Security income,Mean Social Security income (dollars),With Supplemental Security Income,Mean Supplemental Security Income (dollars),With cash public assistance income,Mean cash public assistance income (dollars),With retirement income,Mean retirement income (dollars),With Food Stamp/SNAP benefits,Families,Median family income (dollars),Married-couple family
2010,24310.0,78863.0,92.9,88225.0,21.2,17355.0,2.7,6823.0,2.5,1910.0,10.2,25657.0,5.9,17208.0,90060.0,77.9

In [71]:
INCOME_PAST_12_MONTHS_STATUS.to_csv('data/final/INCOME_PAST_12_MONTHS_STATUS.csv', index=False)

In [72]:
df = pd.read_csv('data/INCOME_PAST_12_MONTHS_STATUS.csv')
df

,Year,Households,Median household income (dollars),With earnings,Mean earnings (dollars),With Social Security income,Mean Social Security income (dollars),With Supplemental Security Income,Mean Supplemental Security Income (dollars),With cash public assistance income,Mean cash public assistance income (dollars),With retirement income,Mean retirement income (dollars),With Food Stamp/SNAP benefits,Families,Median family income (dollars),Married-couple family
0,2010,24310.0,78863.0,92.9,88225.0,21.2,17355.0,2.7,6823.0,2.5,1910.0,10.2,25657.0,5.9,17208.0,90060.0,77.9
1,2011,22701.0,82387.0,94.7,91562.0,18.8,16029.0,2.8,9095.0,3.3,6897.0,7.2,23199.0,2.9,15107.0,90562.0,78.2
2,2012,23724.0,86429.0,92.0,98921.0,19.7,17122.0,2.9,7130.0,1.4,3208.0,10.0,57828.0,4.2,17179.0,89085.0,72.2
3,2013,26959.0,75459.0,89.9,91695.0,25.3,18454.0,4.3,6401.0,1.9,2231.0,8.3,21639.0,7.8,18855.0,82036.0,70.0
4,2014,22226.0,90424.0,91.6,97772.0,22.9,19799.0,3.5,7285.0,2.4,3467.0,11.8,20909.0,7.4,16003.0,96734.0,78.9
5,2015,25286.0,85545.0,92.1,100788.0,20.6,22370.0,4.1,7439.0,2.5,2198.0,10.1,31051.0,7.6,17532.0,94014.0,78.3
6,2017,26139.0,80633.0,88.0,107240.0,26.9,18420.0,3.5,9327.0,2.5,2282.0,8.9,24875.0,5.3,18198.0,88280.0,67.6
7,2019,26642.0,99311.0,90.0,107921.0,25.6,22222.0,2.0,13075.0,2.5,2642.0,22.1,33649.0,6.1,18304.0,102069.0,79.3
8,2021,29191.0,100098.0,87.9,114198.0,26.9,21673.0,3.7,7721.0,5.5,5881.0,19.8,26053.0,7.8,20642.0,113072.0,80.7
9,2022,32190.0,107149.0,88.4,138669.0,25.2,22259.0,2.6,10556.0,1.8,1316.0,21.4,37426.0,10.5,23121.0,116764.0,71.5